### ISSUE TITLE
Release 1.1.0.0

### ISSUE THREAD

**Issue by srijs** [adinapoli/threads-supervisor#19]
Hi there!

I'd like to start using this in another project of mine, which unfortunately is only running on LTS 5, which means I'm dependent on the 1.1.0.0 release being pushed to hackage.

Any change you can do this soonish?

Cheers,
Sam

**Comment by adinapoli** [comment]
Hey @srijs !

I can upload 1.1.0.0 on Hackage this afternoon with ease, but may I ask you why you cannot simply - as an iterim solution - extend your `stack.yml` to add `thread-supervisor-1.1.0.0` in the `extra-deps` section and modify the `packages` section like this?:

```
packages:
- '.'

- location:
    git: git@github.com:adinapoli/threads-supervisor
    commit: f613a88dacf987d54d0dcc92775baf9a196fec6f
```

This will give you `1.1.0.0`.
